trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- task: ECRPushImage@1
  inputs:
    awsCredentials: 'dcm-int-ecr-upload'
    regionName: 'ap-southeast-2'
    imageSource: 'imagename'
    sourceImageName: 'pipelines-javascript-docker'
    repositoryName: 'dcm_rules'
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile